services:
  db:
    image: postgres:15
    container_name: b0-db
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: b0
      POSTGRES_USER: b0
      POSTGRES_DB: b0
    networks:
      - web

  redis:
    image: redis
    container_name: b0-redis
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - redis_data:/data
    networks:
      - web

  db-migration:
    container_name: b0-db-migration
    build:
      context: ./backend
      dockerfile: Dockerfile
    entrypoint: ["./b0", "migrate", "up"]
    depends_on:
      - db
    env_file:
      - ./backend/.env
    ports:
      - 5555:5555
    environment:
      - DB_DRIVER=postgres
      - DB_USER=b0
      - DB_PASSWORD=b0
      - DB_DATABASE=b0
      - DB_HOST=b0-db
      - DB_PORT=5432
    volumes:
      - ./backend/src:/app/src
    networks:
      - web

  backend:
    container_name: b0-api
    build:
      context: ./backend
      dockerfile: Dockerfile
    entrypoint: ["./b0", "serve"]
    depends_on:
      db:
        condition: service_started
      redis:
        condition: service_started
      db-migration:
        condition: service_completed_successfully
    env_file:
      - ./backend/.env
    ports:
      - 5555:5555
    environment:
      - DB_DRIVER=postgres
      - DB_USER=b0
      - DB_PASSWORD=b0
      - DB_DATABASE=b0
      - DB_HOST=b0-db
      - DB_PORT=5432
      - REDIS_HOST=b0-redis
      - AUTH_UI_REDIRECT_URL=http://b0-frontend.local/auth/callback
    volumes:
      - ./backend/src:/app/src
    networks:
      - web
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.backend.rule=Host(`b0-backend.local`)"
      - "traefik.http.routers.backend.entrypoints=web"
      - "traefik.http.services.backend.loadbalancer.server.port=5555"

  frontend:
    container_name: b0-frontend
    restart: unless-stopped
    depends_on:
      - backend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - ./frontend/src:/app/src/ # mounted whole src to avoid missing reload on new files
      - ./frontend/public:/app/public
    env_file: ./frontend/.env
    ports:
      - 3000:3000
    environment:
      - BACKEND_URL=http://b0-backend.local/api
      - PLATFORM_URL=http://b0-backend.local/api/platform
    networks:
      - web
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.frontend.rule=Host(`b0-frontend.local`)"
      - "traefik.http.routers.frontend.entrypoints=web"
      - "traefik.http.services.frontend.loadbalancer.server.port=3000"

volumes:
  postgres-data:
    driver: local
  redis_data:
    driver: local

networks:
  web:
    external: true
