ALTER TABLE "projects" ADD COLUMN "language" TEXT NOT NULL DEFAULT 'Go';

ALTER TABLE "projects" ADD COLUMN "framework" TEXT NOT NULL DEFAULT 'Chi';

ALTER TABLE "projects" ADD COLUMN "port" TEXT NULL DEFAULT NULL;

ALTER TABLE "projects" ADD COLUMN "server_url" TEXT NULL DEFAULT NULL;