import invariant from "tiny-invariant";
import {
  typedjson,
  UseDataFunctionReturn,
  useTypedLoaderData,
} from "remix-typedjson";
import { z } from "zod";
import {
  ActionFunction,
  LoaderFunctionArgs,
  MetaFunction,
  redirect,
} from "@remix-run/node";
import { requireUser } from "~/services/user.server";
import { Project, Projects } from "~/models/project";
import { getProject, getProjects } from "~/services/project.server";
import { RouteErrorDisplay } from "~/components/error-boundary";
import { Outlet } from "@remix-run/react";
import { Endpoint, Endpoints } from "~/models/endpoint";
import { getEndpoints } from "~/services/endpoint.server";

export const ProjectSlugParamSchema = z.object({
  projectSlug: z.string(),
});

export const ProjectSearchSchema = z.object({
  endpoint: z.string().optional(),
});

export const loader = async ({ request, params }: LoaderFunctionArgs) => {
  const { projectSlug } = ProjectSlugParamSchema.parse(params);

  invariant(projectSlug, "No project found in request.");

  const user = await requireUser(request);

  let project: Project | null = null;
  let endpoints: Endpoints = [];
  let endpoint: Endpoint | undefined = undefined;
  let projects: Projects = [];

  const url = new URL(request.url);
  const s = Object.fromEntries(url.searchParams.entries());
  const searchParams = ProjectSearchSchema.parse(s);

  try {
    projects = await getProjects(request);

    project = await getProject(request, projectSlug);

    endpoints = await getEndpoints(request, project.id);
  } catch (err) {
    // redirect or throw not found
    throw new Response(null, {
      status: 404,
      statusText: "Not Found",
    });
  }

  if (searchParams.endpoint) {
    endpoint = endpoints.find((e) => e.id === searchParams.endpoint);
  }

  if (endpoint == undefined && endpoints && endpoints.length > 0) {
    endpoint = endpoints[0];
  }

  return typedjson({
    user,
    projectSlug,
    project,
    projects,
    endpoints,
    endpoint,
  });
};

export const meta: MetaFunction = ({ data }) => {
  let title = "Untitled Project";

  if (data) {
    const { project } = data as UseDataFunctionReturn<typeof loader>;

    title = project.name;
  }
  return [
    {
      title: `${title} | Generated by b0`,
    },
  ];
};

export default function Page() {
  return <Outlet />;
}

export function ErrorBoundary() {
  return <RouteErrorDisplay className="canvas-bg" />;
}
