name: backend-publish

on:
  release:
    types: [published]

permissions:
  contents: write

jobs:
  goreleaser:
    name: Publish backend
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-go@v5
        with:
          go-version: stable
      - uses: goreleaser/goreleaser-action@v6
        with:
          distribution: goreleaser
          version: latest
          args: release --clean
          workdir: ./backend
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - run: |
          mkdir -p dist/artifacts
          cp dist/*.{tar.gz,zip} dist/artifacts
        working-directory: ./backend
      - name: Upload assets
        uses: softprops/action-gh-release@v2
        with:
          files: ./backend/dist/artifacts/*
          fail_on_unmatched_files: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
